# Generated by Django 5.2 on 2025-04-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnector',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='databaseconnector',
            name='date_creation',
            field=models.DateField(),
        ),
    ]
