# Generated by Django 5.2 on 2025-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_databaseconnector_trend_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseconnector',
            name='summary',
        ),
        migrations.AddField(
            model_name='databaseconnector',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
